version: "3"
services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./dist:/usr/src/app/dist
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./.env:/usr/src/app/.env
    ports:
      - 3000:3000
    command: nodemon dist/server.js
    stdin_open: true
    tty: true
