version: "3"
services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./.env:/usr/src/app/.env
    ports:
      - 3000:3000
      - 3010:3010
    command: nodemon dist/server.js
    stdin_open: true
    tty: true
